let num=10;
console.log(num);
let account_balance=20;
console.log(account_balance);
// let account_balance=20;
console.log(typeof account_balance);
let str= "rohit negi";
console.log(str);
let statement=true;
console.log(statement);
let account;
console.log(account);
let balance=null;
console.log(balance);
let a = 37932984324932874683564835n;
console.log(a);
console.log(Number.MAX_SAFE_INTEGER);
console.log(Number.MIN_SAFE_INTEGER);