const arr=[2,35,2,7,8,9,"Mohit",true,7];
console.log(arr);
console.log(arr.length);
console.log(arr[1]);
console.log(arr.at(-1));
const newarr= structuredClone(arr);
console.log(newarr);
console.log(newarr==arr);
arr.push(30);
arr.push(40);
console.log(arr);
arr.pop();
console.log(arr);
arr.unshift(10);
console.log(arr);
arr.shift();
console.log(arr);
delete arr[0];
console.log(arr);
console.log(arr.indexOf(7));
console.log(arr.lastIndexOf(7));
console.log(arr.includes(9));
console.log(arr.slice(2,4));
// console.log(arr.splice(2,5));
// console.log(arr);
arr.splice(0,4,"money",90);
console.log(arr);
console.log(arr.toString());
console.log(arr.join("*"));
// concat
let arr3=[1,2,3];
let arr4=arr.concat(arr3);
console.log(arr4);
let arr2d=[[1,2,3],[4,5,6],[7,8,9]];
console.log(arr2d);
let arr1d=arr2d.flat();
console.log(arr1d);
console.log(Array.isArray(arr1d));
